name: BWO
description: An infinity procedural Game With Firebase

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flame: ^0.22.0
  extended_image: ^0.7.3-dev
  fast_noise: ^0.1.3+1
  sensors: '>=0.4.2+2 <2.0.0'
  flutter_socket_io: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      #player
      - assets/images/human/male1/walk/forward.png
      - assets/images/human/male1/walk/backward.png
      - assets/images/human/male1/walk/left.png
      - assets/images/human/male1/walk/right.png
      - assets/images/human/male1/walk/forward_left.png
      - assets/images/human/male1/walk/forward_right.png
      - assets/images/human/male1/walk/backward_left.png
      - assets/images/human/male1/walk/backward_right.png
      
      - assets/images/human/male1/attack/forward.png
      - assets/images/human/male1/attack/backward.png
      - assets/images/human/male1/attack/left.png
      - assets/images/human/male1/attack/right.png
      - assets/images/human/male1/attack/forward_left.png
      - assets/images/human/male1/attack/forward_right.png
      - assets/images/human/male1/attack/backward_left.png
      - assets/images/human/male1/attack/backward_right.png

      # male2
      - assets/images/human/male2/walk/forward.png
      - assets/images/human/male2/walk/backward.png
      - assets/images/human/male2/walk/left.png
      - assets/images/human/male2/walk/right.png
      - assets/images/human/male2/walk/forward_left.png
      - assets/images/human/male2/walk/forward_right.png
      - assets/images/human/male2/walk/backward_left.png
      - assets/images/human/male2/walk/backward_right.png

      - assets/images/human/male2/attack/forward.png
      - assets/images/human/male2/attack/backward.png
      - assets/images/human/male2/attack/left.png
      - assets/images/human/male2/attack/right.png
      - assets/images/human/male2/attack/forward_left.png
      - assets/images/human/male2/attack/forward_right.png
      - assets/images/human/male2/attack/backward_left.png
      - assets/images/human/male2/attack/backward_right.png
      
      # female1
      - assets/images/human/female1/walk/forward.png
      - assets/images/human/female1/walk/backward.png
      - assets/images/human/female1/walk/left.png
      - assets/images/human/female1/walk/right.png
      - assets/images/human/female1/walk/forward_left.png
      - assets/images/human/female1/walk/forward_right.png
      - assets/images/human/female1/walk/backward_left.png
      - assets/images/human/female1/walk/backward_right.png

      - assets/images/human/female1/attack/forward.png
      - assets/images/human/female1/attack/backward.png
      - assets/images/human/female1/attack/left.png
      - assets/images/human/female1/attack/right.png
      - assets/images/human/female1/attack/forward_left.png
      - assets/images/human/female1/attack/forward_right.png
      - assets/images/human/female1/attack/backward_left.png
      - assets/images/human/female1/attack/backward_right.png
      
      # female2
      - assets/images/human/female2/walk/forward.png
      - assets/images/human/female2/walk/backward.png
      - assets/images/human/female2/walk/left.png
      - assets/images/human/female2/walk/right.png
      - assets/images/human/female2/walk/forward_left.png
      - assets/images/human/female2/walk/forward_right.png
      - assets/images/human/female2/walk/backward_left.png
      - assets/images/human/female2/walk/backward_right.png
      
      # female3
      - assets/images/human/female3/walk/forward.png
      - assets/images/human/female3/walk/backward.png
      - assets/images/human/female3/walk/left.png
      - assets/images/human/female3/walk/right.png
      - assets/images/human/female3/walk/forward_left.png
      - assets/images/human/female3/walk/forward_right.png
      - assets/images/human/female3/walk/backward_left.png
      - assets/images/human/female3/walk/backward_right.png

      # female4
      - assets/images/human/female4/walk/forward.png
      - assets/images/human/female4/walk/backward.png
      - assets/images/human/female4/walk/left.png
      - assets/images/human/female4/walk/right.png
      - assets/images/human/female4/walk/forward_left.png
      - assets/images/human/female4/walk/forward_right.png
      - assets/images/human/female4/walk/backward_left.png
      - assets/images/human/female4/walk/backward_right.png

      - assets/images/human/female4/attack/forward.png
      - assets/images/human/female4/attack/backward.png
      - assets/images/human/female4/attack/left.png
      - assets/images/human/female4/attack/right.png
      - assets/images/human/female4/attack/forward_left.png
      - assets/images/human/female4/attack/forward_right.png
      - assets/images/human/female4/attack/backward_left.png
      - assets/images/human/female4/attack/backward_right.png

       # female5
      - assets/images/human/female5/walk/forward.png
      - assets/images/human/female5/walk/backward.png
      - assets/images/human/female5/walk/left.png
      - assets/images/human/female5/walk/right.png
      - assets/images/human/female5/walk/forward_left.png
      - assets/images/human/female5/walk/forward_right.png
      - assets/images/human/female5/walk/backward_left.png
      - assets/images/human/female5/walk/backward_right.png

      #Enemy - mini-skull
      - assets/images/enemys/miniskull/walk/forward.png
      - assets/images/enemys/miniskull/walk/backward.png
      - assets/images/enemys/miniskull/walk/left.png
      - assets/images/enemys/miniskull/walk/right.png
      - assets/images/enemys/miniskull/walk/forward_left.png
      - assets/images/enemys/miniskull/walk/forward_right.png
      - assets/images/enemys/miniskull/walk/backward_left.png
      - assets/images/enemys/miniskull/walk/backward_right.png
      
      - assets/images/enemys/miniskull/attack/forward.png
      - assets/images/enemys/miniskull/attack/backward.png
      - assets/images/enemys/miniskull/attack/left.png
      - assets/images/enemys/miniskull/attack/right.png
      - assets/images/enemys/miniskull/attack/forward_left.png
      - assets/images/enemys/miniskull/attack/forward_right.png
      - assets/images/enemys/miniskull/attack/backward_left.png
      - assets/images/enemys/miniskull/attack/backward_right.png

      #enviroment
      - assets/images/trees/tree01.png
      - assets/images/trees/tree02.png
      - assets/images/trees/tree03.png
      - assets/images/trees/tree04.png
      - assets/images/enviroment/floor1.png
      - assets/images/enviroment/floor2.png
      - assets/images/enviroment/floor3.png
      - assets/images/enviroment/grass1.png
      - assets/images/enviroment/grass2.png
      - assets/images/enviroment/grass3.png
      - assets/images/enviroment/grass4.png
      - assets/images/enviroment/grass5.png
      - assets/images/enviroment/grass6.png
      - assets/images/enviroment/grass7.png
      - assets/images/enviroment/grass8.png
      - assets/images/enviroment/grass9.png
      - assets/images/enviroment/grass10.png
      - assets/images/enviroment/grass11.png
      - assets/images/enviroment/grass12.png
      - assets/images/enviroment/grass13.png
      - assets/images/enviroment/grass14.png
      - assets/images/shadown.png
      - assets/images/shadown_large.png
      - assets/images/effects/ripple.png
      - assets/images/effects/walk_grass.png
      - assets/images/effects/rip.png

      #items
      - assets/images/items/apple3.png
      - assets/images/items/apple_green.png
      - assets/images/items/orange.png
      - assets/images/items/log.png

      # ui
      - assets/images/ui/backpaper.png
      - assets/images/ui/backpaper1.png
      - assets/images/ui/bag.png
      - assets/images/ui/bag_open.png
      - assets/images/ui/bag2.png
      - assets/images/ui/bag2_open.png
      - assets/images/ui/stomach.png
      - assets/images/ui/stomach_back.png

      # sounds
      - assets/audio/recovery.mp3
      - assets/audio/footstep_grass1.mp3
      - assets/audio/footstep_grass2.mp3
      - assets/audio/footstep_sand_beech.mp3
      - assets/audio/footstep_water_splash.mp3
      - assets/audio/footstep_water_splash2.mp3
      - assets/audio/swim_1.mp3
      - assets/audio/impact_tree.mp3
      - assets/audio/impact_tree2.mp3
      - assets/audio/punch.mp3
      - assets/audio/pickup_item1.mp3
      - assets/audio/pickup_item2.mp3
      - assets/audio/power_up.mp3
      - assets/audio/items/eating_apple.mp3

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Pixeled
      fonts:
        - asset: fonts/Pixeled.ttf
    - family: Minecraft
      fonts:
        - asset: fonts/Minecraft.ttf
    - family: Blocktopia
      fonts:
        - asset: fonts/Blocktopia.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages